resources:
- name: openbank_apis
  type: solutions.api
  properties:
    inputs:
    - name: org
      prompt: Edge Org name
    - name: username
      prompt: Username
      ifNotPresent: token
    - name: password
      prompt: Password
      ifNotPresent: token
    - name: env
      prompt: Edge Org Environment
    - name: usergrid_org
      prompt: BaaS Org name
    - name: usergrid_app
      prompt: BaaS App name
    - name: usergrid_client_id
      prompt: BaaS Org Client Id
    - name: usergrid_secret
      prompt: BaaS Org Client Secret
    configurations:
    - env: test
      baas_host: https://apibaas-trial.apigee.net
      edge_host: https://api.enterprise.apigee.com
      sms_endpoint: https://rest.nexmo.com/sms/json
    - env : prod
      baas_host: https://apibaas-trial.apigee.net
      edge_host: https://api.enterprise.apigee.com
      sms_endpoint: https://rest.nexmo.com/sms/json

    edgeOrg:
    script: gulpfile.js
    basePath: .
    dependencies:
#    - name: session
#      type: proxy
#      url: git@revision.aeip.apigee.net:solution-commons/session.git
#      version: v1.0.0
    dataSources:
    - name: default
      orgName: '{{usergrid_org}}'
      appName: '{{usergrid_app}}'
      appClientId: '{{usergrid_client_id}}'
      appSecret: '{{usergrid_secret}}'
    subResources:
    - name: baas_data_load
      type: baasLoadData
      items:
      - name: banks
        permissions: ['get,post,delete:banks','get,post,delete:banks/*','get,post,delete:banks/**']
      - name: transactions
        permissions: ['get,post,delete:transactions','get,post,delete:transactions/*','get,post,delete:transactions/**']
      - name: accounts
        file: setup/data/accounts.json
        permissions: ['get,post,delete:accounts','get,post,delete:accounts/*','get,post,delete:accounts/**']
      - name: customers
        file: setup/data/customers.json
        permissions: ['get,post,delete:customers','get,post,delete:customers/*','get,post,delete:customers/**']
      - name: locations
        file: setup/data/locations.json
        permissions: ['get,post,delete:locations','get,post,delete:locations/*','get,post,delete:locations/**']
      - name: products
        file: setup/data/products.json
        permissions: ['get,post,delete:products','get,post,delete:products/*','get,post,delete:products/**']
    - name: create_connections
      type: baasConnection
      items:
      - name: connections
        file: setup/connections.json
    - name: cacheResources
      type: cache
      items:
      - name: consent-session-cache
        payload: '{ "name": "consent-session-cache"}'
      - name: application-session-cache
        payload: '{ "name": "application-session-cache"}'
      - name: sms-token-cache
        payload: '{ "name": "sms-token-cache"}'
      - name: nonce-cache
        payload: '{ "name": "nonce-cache"}'
    - name: replaceorgvalues
      type: configSubstitutions
      items:
      - name: baasBasePath
        filePaths: ['src/gateway/accounts-connector/target/apiproxy/policies/Assign.TargetURL.xml','src/gateway/locations-connector/target/apiproxy/policies/Assign.TargetURL.xml','src/gateway/products-connector/target/apiproxy/policies/Assign.TargetURL.xml','src/gateway/transfers-connector/target/apiproxy/policies/Callout.AddTransactionToAccount.xml','src/gateway/transfers-connector/target/apiproxy/targets/default.xml','src/gateway/userinfo/target/apiproxy/policies/Callout.GetUserDetails.xml','src/gateway/authentication-connector/target/apiproxy/targets/default.xml']
        value: '{{ baas_host }}/{{ usergrid_org }}/{{ usergrid_app }}'
      - name: redirectConsentOauth
        filePaths: ['src/gateway/oauth/target/apiproxy/policies/Assign.RedirectConsentApp.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/internal/consent?sessionid={messageid}'
      - name: redirectConsentTransfers
        filePaths: ['src/gateway/transfers/target/apiproxy/policies/Assign.RedirectConsentApp.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/internal/transfer-consent?sessionid={messageid}'
      - name: edgeBasePath
        filePaths: ['src/gateway/transfers/target/apiproxy/policies/Callout-Complete-Transfer.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net'
      - name: sms_endpoint
        filePaths: ['src/gateway/sms-token/target/apiproxy/targets/confirmation.xml','src/gateway/sms-token/target/apiproxy/targets/default.xml']
        value: '{{ sms_endpoint }}'
    - name: bank_apis
      type: proxy
      items:
      - name: accounts
      - name: accounts-connector
      - name: authentication-connector
      - name: locations
      - name: locations-connector
      - name: oauth
      - name: session
      - name: sms-token
      - name: transfers
      - name: transfers-connector
      - name: userinfo
      - name: products
      - name: products-connector

    - name: developers
      type: developer
      items:
      - payload: '{"email":"openbank@apigee.net", "firstName":"OpenBank","lastName":"Developer","userName":"openbank"}'
        email: openbank@apigee.net
    - name: apiProducts
      type: product
      items:
      - payload: '{"approvalType":"auto", "displayName":"Open Data APIs","name":"open_data_apis","environments":["test","prod"],"scopes":["openid", "atms", "branches"], "proxies":["oauth", "locations"]}'
        name: open_data_apis
      - payload: '{"approvalType":"auto", "displayName":"Payment Transfer APIs","name":"payment_transfer_apis","environments":["test","prod"],"scopes":["openid", "accounts", "transfer", "payment"], "proxies":["oauth", "transfers", "accounts"]}'
        name: payment_transfer_apis
      - payload: '{"approvalType":"auto", "displayName":"Account Access APIs","name":"account_access_apis","environments":["test","prod"],"scopes":["openid", "accounts", "accounts-info", "accounts-balance", "accounts-transactions"], "proxies":["oauth", "accounts"]}'
        name: account_access_apis
      - payload: '{"approvalType":"auto", "attributes":[{"name":"access","value":"private"}], "displayName":"Internal Consent APIs","name":"internal_consent_apis","environments":["test","prod"],"scopes":[], "proxies":["session", "sms-token", "authentication-connector", "oauth"]}'
        name: internal_consent_apis
    - name: developerApps
      type: app
      items:
      - name: AISP_App
        payload: '{"name":"AISP_App","callback":"http://localhost/","email":"openbank@apigee.net","apiProducts":"account_access_apis"}'
        assignResponse:
        - from: credentials.0.consumerKey
          to: apiKey_AISP
        - from: credentials.0.consumerSecret
          to: apiSecret_AISP
      - name: PISP_App
        payload: '{"name":"PISP_App","callback":"http://localhost/","email":"openbank@apigee.net","apiProducts":"payment_transfer_apis"}'
        assignResponse:
        - from: credentials.0.consumerKey
          to: apiKey_PISP
        - from: credentials.0.consumerSecret
          to: apiSecret_PISP
      - name: internal_consent_app
        payload: '{"name":"internal_consent_app","callback":"http://localhost/","email":"openbank@apigee.net","apiProducts":"internal_consent_apis"}'
        assignResponse:
        - from: credentials.0.consumerKey
          to: apiKey_ICA
      - name: Opendata_App
        payload: '{"name":"Opendata_App","callback":"http://localhost/","email":"openbank@apigee.net","apiProducts":"open_data_apis"}'

    - name: replace_consent_app_key
      type: configSubstitutions
      items:
      - name: consentAppKey
        filePaths: ['src/gateway/consent-app/target/apiproxy/resources/node/config.json','src/gateway/consent-app-transfers/target/apiproxy/resources/node/config.json']
        value: '{{ apiKey_ICA }}'
      - name: edgeBasePath
        filePaths: ['src/gateway/consent-app/target/apiproxy/resources/node/config.json','src/gateway/consent-app-transfers/target/apiproxy/resources/node/config.json']
        value: 'https://{{ org }}-{{ env }}.apigee.net'
    - name: consent_apis
      type: proxy
      items:
      - name: consent-app
      - name: consent-app-transfers
    - name: copyTestConfigTemplate
      type: localCommand
      items: 
      - name: testConfig
        cmd: cp ./test/config.js.template ./test/config.js
    - name: replaceTestScript
      type: configSubstitutions
      items:
      - name: edgeBasePath
        filePaths: ['test/config.js'] 
        value: 'https://{{ org }}-{{ env }}.apigee.net'
      - name: apiKey_AISP
        filePaths: ['test/config.js'] 
        value: '{{ apiKey_AISP }}'
      - name: apiSecret_AISP
        filePaths: ['test/config.js'] 
        value: '{{ apiSecret_AISP }}'
      - name: apiKey_PISP
        filePaths: ['test/config.js']
        value: '{{ apiKey_PISP }}'
      - name: apiSecret_PISP
        filePaths: ['test/config.js']
        value: '{{ apiSecret_PISP }}'



